name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DATABASE_URL: 'https://fake.com'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.15.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies with Yarn
        run: yarn install --frozen-lockfile

      - name: Run TypeScript type checking
        run: yarn run type-check

      - name: Run lint
        run: yarn run lint
